-- create table houses (
--     id serial primary key,
--     name varchar(30),
--     address varchar(100),
--     city varchar(100),
--     state varchar(2),
--     zip integer,
--     img text,
--     mortgage decimal,
--     rent decimal
-- )

-- insert into houses (name, address, city, state, zip, img, mortgage, rent)
-- values ('Brendan', '54-227 Kaipaupau Loop' , 'Hauula', 'HI', 96717, 'image', 3219.99, 500.22);
